CC=/usr/bin/cc
CFLAGS=-DCMAKE_PROJECT_VERSION=\"1.0.3\" -Werror -Wall -std=gnu99\
	-I../include\
	-Ibuild/include\
	-I../applications/zpc/components/zpc_stdin/include\
	-I../applications/zpc/components/zpc_utils/include\
	-I../components/uic_log/include\
	-I../components/uic_config/include\
	-I../applications/zpc/components/zpc_attribute_store/include\
	-I../applications/zpc/components/zwave_definitions/include\
	-I../components/uic_attribute_store/include\
	-I../components/uic_datastore/include\
	-I../applications/zpc/components/zwave_controller/include\
	-I../applications/zpc/components/zwave_controller/src\
	-I../applications/zpc/components/zwave_rx/include\
	-I../applications/zpc/components/zpc_config/include\
	-I../applications/zpc/components/zwave_tx/include\
	-I../applications/zpc/components/zwave_api/include\
	-I../components/uic_contiki/core\
	-I../components/uic_contiki/platform/posix\
	-I../components/uic_contiki/core/dev\
	-I../components/uic_contiki/core/lib\
	-I../components/uic_contiki/core/sys\
	-I../components/uic_contiki/cpu/native\
	-I../applications/zpc/components/zwave_tx_groups/include\
	-I../applications/zpc/components/zwave_network_management/include\
	-I../applications/zpc/components/zwave_security_validation/include\
	-I../applications/zpc/components/s2/include\
	-I../applications/zpc/components/s0/include\
	-I../applications/zpc/components/zwave_transports/include\
	-I../applications/zpc/components/zwave_transports/transport_service/include\
	-I../applications/zpc/components/zwave_tx_scheme_selector/include\
	-I../applications/zpc/components/zwave_command_classes/include\
	-I../components/uic_attribute_utils/include\
	-I../components/uic_attribute_resolver/include\
	-I../components/uic_multi_invoke/include\
	-I../applications/zpc/components/zpc_attribute_resolver/include\
	-I../applications/zpc/components/zwave_command_handler/include\
	-Ibuild/applications/zpc\
	-Ibuild/applications/zpc/components/zwave_command_classes/src-gen\
	-I../applications/zpc/components/zwave_command_classes/src\
	-I../components/uic_ota/platform/posix\
	-I../components/uic_ota/include\
	-I../components/uic_definitions/include\
	-I../components/uic_mqtt/include\
	-I../components/uic_main_fd/include\
	-I../applications/zpc/components/ucl_mqtt/include\
	-I../applications/zpc/components/ucl_definitions/include\
	-I../components/uic_stdin/include\
	-I../applications/zpc/components/zpc_datastore/include\
	-I../applications/zpc/components/zwave_smartstart_management/include\
	-I../applications/zpc/components/zwave_smartstart_management/../s2/libs/zw-libs2/include\
	-I../applications/zpc/components/network_monitor/include\
	-I../components/uic_smartstart_management/include\
	-I../components/uic_smartstart_management/mocks/.\
	-I../components/uic_smartstart_management/mocks/../include\
	-I../applications/zpc/components/dotdot_mapper/include\
	-Ibuild/components/uic_dotdot_mqtt/include\
	-Ibuild/components/uic_dotdot/include\
	-Ibuild/applications/zpc/components/dotdot_mapper/include\
	-I../applications/zpc/components/dotdot_mqtt_topics_handler/include\
	-Ibuild/applications/zpc/components/dotdot_mqtt_topics_handler/include\
	-I../components/uic_main/include\
	-I../components/uic_attribute_mapper/include\
	-I../applications/zpc/components/zcl_cluster_servers/include\

LDLIBS	=\
		libs/libzpc_stdin.a\
		libs/libzwave_controller.a\
		libs/libzpc_datastore.a\
		libs/libzwave_s2.a\
		libs/libzwave_network_management.a\
		libs/libzwave_smartstart_management.a\
		libs/libzwave_transports.a\
		libs/libzwave_command_handler.a\
		libs/libzwave_command_classes.a\
		libs/libnetwork_monitor.a\
		libs/libzpc_attribute_resolver.a\
		libs/libzpc_attribute_store.a\
		libs/libdotdot_mapper.a\
		libs/libdotdot_mqtt_topics_handler.a\
		libs/libuic_main.so\
		libs/libuic_attribute_mapper.so\
		libs/libucl_mqtt.a\
		libs/libzcl_cluster_servers.a\
		libs/libuic_smartstart_management.so\
		libs/libzcl_group_cluster_server.a\
		libs/libdotdot_mqtt_topics_handler.a\
		libs/libzcl_cluster_servers.a\
		libs/libzcl_group_cluster_server.a\
		libs/libzcl_OTA_cluster_server.a\
		libs/libzwave_command_classes.a\
		libs/libuic_attribute_utils.so\
		libs/libzpc_attribute_resolver.a\
		libs/libuic_ota.so\
		libs/libucl_node_state.a\
		libs/libucl_mqtt_node_interview.a\
		libs/libucl_network_management.a\
		libs/libucl_nm_neighbor_discovery.a\
		libs/libzwave_controller.a\
		libs/libzwave_s2.a\
		libs/libzwave_network_management.a\
		libs/libzwave_transports.a\
		libs/libzwave_command_handler.a\
		libs/libzpc_attribute_store.a\
		libs/libzpc_utils.a\
		libs/libzwave_tx_groups.a\
		libs/libzwave_rx.a\
		libs/libzwave_tx.a\
		libs/libzwave_tx_scheme_selector.a\
		libs/libzwave_security_validation.a\
		libs/libzwave_api.a\
		libs/libzwave_s0.a\
		libs/libtransport_service.a\
		libs/libzwave_handlers.a\
		libs/libdotdot_attributes.a\
		libs/libzwave_controller.a\
		libs/libzwave_s2.a\
		libs/libzwave_network_management.a\
		libs/libzwave_transports.a\
		libs/libzwave_command_handler.a\
		libs/libzpc_attribute_store.a\
		libs/libzpc_utils.a\
		libs/libzwave_tx_groups.a\
		libs/libzwave_rx.a\
		libs/libzwave_tx.a\
		libs/libzwave_tx_scheme_selector.a\
		libs/libzwave_security_validation.a\
		libs/libzwave_api.a\
		libs/libzwave_s0.a\
		libs/libtransport_service.a\
		libs/libzwave_handlers.a\
		libs/libdotdot_attributes.a\
		libs/libs2_controller.a\
		libs/libs2crypto.a\
		libs/libaes.a\
		libs/libzpc_config.a\
		libs/libuic_attribute_resolver.so\
		libs/libuic_dotdot_mqtt.so\
		libs/libuic_stdin.so\
		libs/libuic_mqtt.so\
		libs/libuic_main_fd.so\
		libs/libuic_contiki.so\
		libs/libuic_mqtt_client.so\
		libs/libuic_mqtt_wrapper.so\
		libs/libuic_contiki_platform.so\
		libs/libuic_attribute_store.so\
		libs/libuic_datastore.so\
		libs/libuic_log.so\
		libs/libuic_config.so\
		-pthread -ldl

LDFLAGS	=-pipe -Werror -Wall

%.o: %.c $(DEPS)
	$(CC) -c -o $@ $< $(CFLAGS)
zpc: main.o 
	/usr/bin/c++ $(LDFLAGS) -o zpc main.o -Wl,-rpath,/home/richard/disks/sdb6/2023/pytronic/UnifySDK/zpc-jni/libs $(LDLIBS)
